### PR TITLE
Building Overview

### PR DESCRIPTION
**Pull request by KarinaSandur**
Implemented the front-end of the building profile page which can be found in the 'Overview' tab in the /building-info url.

This PR closes task #103.

### CODE REVIEW

**Review by CarlaShawi — APPROVED** [review]

**Review by Ziadsharkos — APPROVED** [review]

**Review by Tharsipa — APPROVED** [review]

**Review by amczuboka — APPROVED** [review]
Looks good to me

**Review by npiperni — APPROVED** [review]
lgtm

**Review by IsabelleCzuboka — APPROVED** [review]
Looks good, I like how the booking is already there on the page!

**Review by PaulFarid — APPROVED** [review]

**Review by Guillaume-Lachapelle — APPROVED** [review]
Looks great!

**Review by Holyvert — APPROVED** [review]

**Pull request merged**
