### PR TITLE
61 budget report

### LINKED ISSUE #65: Task: Implement back-end for "Budget Report" page.
#61

### LINKED ISSUE #74: Task: Create user acceptance for "Budget Report" page.
#61

### PR DESCRIPTION
**Pull request by npiperni**
- Adds budget report page
- Adds cypress test for budget report page

closes #65 
closes #74

### CODE REVIEW

**Review by Guillaume-Lachapelle — APPROVED** [review]
Looks good! Maybe add a button to access the page more easily

**Comment by npiperni** [comment]
Ignore the "useless" variables from the sonarcloud report. They are required for the spec tests.

**Review by Ziadsharkos — APPROVED** [review]

**Review by Tharsipa — APPROVED** [review]

**Review by IsabelleCzuboka — APPROVED** [review]
All good to me

**Review by amczuboka — CHANGES_REQUESTED** [review]
Iv'e tested with a company user that owns this buildings 
image
which has two operations. Yet, no condo fee revenue or operation costs appear. 
image

**Comment by npiperni** [comment]
> Iv'e tested with a company user that owns this buildings image which has two operations. Yet, no condo fee revenue or operation costs appear. image

The operations interface has been modified in 68a58504642d26e9d84129514d6ba5a141960b46 so operations added before this are not fetched properly. Try deleting the old operations from firebase and add them again

**Review by amczuboka — APPROVED** [review]
Looks good

**Review by KarinaSandur — APPROVED** [review]

**Review by Holyvert — APPROVED** [review]

**Pull request merged**
