### PR TITLE
#30 #31 add new building

### LINKED ISSUE #30: Task: Implement front-end for creating a profile for a complex building.
A condo manager can create a profile detailing the complex building in question. Look at requirement documentation for those specific fields.

### LINKED ISSUE #31: Task: Implement back-end for creating a profile on a complex building

### PR DESCRIPTION
**Pull request by Holyvert**
Did front/back end to add a new building.
Did related unit test for the added components
Closes #31
Closes #30
Relatade #128 #7

### CODE REVIEW

**Review by npiperni — APPROVED** [review]

**Review by amczuboka — CHANGES_REQUESTED** [review]
Great job on the UI. Great commenting of the code. Resizable. One thing. Please title the add new locker and parking dialogs properly. At the moment, they all say "add condos"

**Review by Guillaume-Lachapelle — CHANGES_REQUESTED** [review]
When we click on "add condo" and then click outside of the dialog, a weird bug happens with the bottom, there's like an invisible padding that hides the bottom of the page

image

**Review by KarinaSandur — CHANGES_REQUESTED** [review]
Looks really nice! Minor thing but please fix these typos.
image

**Review by Guillaume-Lachapelle — APPROVED** [review]

**Review by amczuboka — APPROVED** [review]
Typos and styling have been fixed

**Review by KarinaSandur — APPROVED** [review]

**Review by IsabelleCzuboka — APPROVED** [review]
Looks good

**Review by Ziadsharkos — APPROVED** [review]

**Pull request merged**
