### PR TITLE
User Acceptance Tests for registering unit-locker-parking

### LINKED ISSUE #112: Task: Create user acceptance test for registering a unit with an account with key.

### LINKED ISSUE #113: Task: Create user acceptance test for registering a parking and locker with an account with key.

### PR DESCRIPTION
**Pull request by PaulFarid**
closes #112 
closes #113
User Acceptance Tests for registering unit-locker-parking

One cypress test fails but is fixed in [Fixed my employees cypress test #199](https://github.com/amczuboka/Decagon-CondoManagementSystem/pull/199)

### CODE REVIEW

**Review by Ziadsharkos — APPROVED** [review]

**Review by amczuboka — CHANGES_REQUESTED** [review]
It looks like the build is failing on your cypress test. Try rerunning the test on GitHub if it continuously works on your local machine. 
Also, where does your test de-register the properties so that your test passes every time?

**Review by Holyvert — APPROVED** [review]

**Comment by Holyvert** [comment]
> It looks like the build is failing on your cypress test. Try rerunning the test on GitHub if it continuously works on your local machine. Also, where does your test de-register the properties so that your test passes every time?



> It looks like the build is failing on your cypress test. Try rerunning the test on GitHub if it continuously works on your local machine. Also, where does your test de-register the properties so that your test passes every time?



> It looks like the build is failing on your cypress test. Try rerunning the test on GitHub if it continuously works on your local machine. Also, where does your test de-register the properties so that your test passes every time?



> It looks like the build is failing on your cypress test. Try rerunning the test on GitHub if it continuously works on your local machine. Also, where does your test de-register the properties so that your test passes every time?

For some reason it works on the computer but not on GitHub maybe a synchronization issue

**Review by npiperni — APPROVED** [review]

**Review by CarlaShawi — APPROVED** [review]

**Review by Tharsipa — APPROVED** [review]

**Review by Guillaume-Lachapelle — APPROVED** [review]

**Review by IsabelleCzuboka — APPROVED** [review]
Looks good

**Review by KarinaSandur — APPROVED** [review]

**Comment by Holyvert** [comment]
> It looks like the build is failing on your cypress test. Try rerunning the test on GitHub if it continuously works on your local machine. Also, where does your test de-register the properties so that your test passes every time?

https://github.com/amczuboka/Decagon-CondoManagementSystem/pull/197/commits/2b8d0343c31e63c87e68e23fe1c6d6d1e2c0b599

**Comment by Holyvert** [comment]
image

**Review by Guillaume-Lachapelle — APPROVED** [review]

**Pull request merged**
