### PR TITLE
Booking back end

### LINKED ISSUE #69: Task: Implement back-end for "Reservations" page for owners and renters.

### LINKED ISSUE #73: Task: Implement back-end for "Reservations" page for condo managers.

### LINKED ISSUE #78: Task: Implement back-end for "Bookings" page for owners and renters.

### PR DESCRIPTION
**Pull request by Holyvert**
done with
@KarinaSandur 
Closes #78
Closes #73 
Closes #69

Public user can reserve a booking if they are a owner or renter.
image

Companies can look at the full schedule
image

### CODE REVIEW

**Review by KarinaSandur — APPROVED** [review]

**Review by npiperni — APPROVED** [review]

**Review by Guillaume-Lachapelle — APPROVED** [review]

**Review by IsabelleCzuboka — APPROVED** [review]
Looks good

**Review by amczuboka — CHANGES_REQUESTED** [review]
I have a user that has rented a condo from 2 different buildings. If the user makes a reservation for one facility in one building, the reservation will appear as well in another building's reservation tab. This is confusing because how do they know which reservation is for which building. Add BuildingID to the booking's interface to filter which booking belongs to the building to display properly in the 'Reservations" tab or make the 'Reservations' tab global and add building name to the booking component.

**Review by Tharsipa — APPROVED** [review]

**Comment by Holyvert** [comment]
> I have a user that has rented a condo from 2 different buildings. If the user makes a reservation for one facility in one building, the reservation will appear as well in another building's reservation tab. This is confusing because how do they know which reservation is for which building. Add BuildingID to the booking's interface to filter which booking belongs to the building to display properly in the 'Reservations" tab or make the 'Reservations' tab global and add building name to the booking component. image
fixed
https://github.com/amczuboka/Decagon-CondoManagementSystem/pull/210/commits/b4fce5e75bc3cbc59d4e9975680c08f859a2fbf9

**Review by amczuboka — APPROVED** [review]

**Comment by npiperni** [comment]
@Holyvert 
Next time remember to check for nulls and we won't get random errors LOL
image

**Pull request merged**
