### PR TITLE
small changes for sonar

### PR DESCRIPTION
**Pull request by Holyvert**
#203 
And major changes to the header
Fixes Individual condo cypress

### CODE REVIEW

**Review by Guillaume-Lachapelle — CHANGES_REQUESTED** [review]
On smaller screen, the "Home" link doesn't appear first in the dropdown. Also, the logo and the profile picture appear on two separate rows, one on top of the other (which hides some content in certain pages).

image

**Review by Guillaume-Lachapelle — APPROVED** [review]

**Comment by npiperni** [comment]
image
Text is no longer bold?

**Review by npiperni — APPROVED** [review]
Keep in mind there will be a conflict with the budget report button in the budget report branch

**Review by CarlaShawi — APPROVED** [review]

**Review by Tharsipa — APPROVED** [review]

**Review by IsabelleCzuboka — APPROVED** [review]
Looks good

**Review by KarinaSandur — APPROVED** [review]

**Review by Ziadsharkos — APPROVED** [review]

**Pull request merged**
