### PR TITLE
#192 #193 Requests Follow-Up and Modifications

### LINKED ISSUE #192: Modify requests to send to employee with that role instead of company

### LINKED ISSUE #193: Add a way to notify public users of their request status

### PR DESCRIPTION
**Pull request by Guillaume-Lachapelle**
Added request status for notifications

When the status is changed, the public user who made the request is notified.

Send requests to employee with that role instead of company

If no employee with that role is found, the notification is sent to the company.

Added and fixed tests

One cypress test fails but is fixed in [Fixed my employees cypress test #199](https://github.com/amczuboka/Decagon-CondoManagementSystem/pull/199)

closes #192 
closes #193

### CODE REVIEW

**Review by npiperni — CHANGES_REQUESTED** [review]
It's good. I like the feedback when the request status is updated Only thing is noticed is it sends the requests to every employee with the associated role, but should also only send it to employees assigned to that particular building

**Comment by Guillaume-Lachapelle** [comment]
> It's good. I like the feedback when the request status is updated Only thing is noticed is it sends the requests to every employee with the associated role, but should also only send it to employees assigned to that particular building

New code was just pushed to fix this issue ;)

**Review by npiperni — APPROVED** [review]

**Review by CarlaShawi — APPROVED** [review]

**Review by Holyvert — APPROVED** [review]

**Review by amczuboka — APPROVED** [review]
Looks great

**Review by KarinaSandur — APPROVED** [review]

**Review by IsabelleCzuboka — APPROVED** [review]
changes are good

**Review by Ziadsharkos — APPROVED** [review]

**Pull request merged**
